services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    container_name: redis
    ports:
      - "6379:6379"
  utask:
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
    container_name: utask
    volumes:
      - .:/build
    ports:
      - "3000:3000"
    depends_on:
      - redis
